import type {Metadata} from "next";
import {Geist, Geist_Mono, Inter, Nunito, Roboto} from "next/font/google";
import "./globals.css";
import Footer from "@/app/Footer";
import NavBar from "@/app/NavBar";


const inter = Inter(
    {
        subsets: ['latin'],
        variable: '--font-inter',
    }
)

const nunito = Nunito({
    subsets: ['latin'],
    variable: '--font-nunito',
});

const roboto = Roboto({
    subsets: ['latin'],
    variable: '--font-roboto',
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${inter.variable} ${roboto.variable} ${nunito.variable} antialiased`}

        >
        <div className="min-h-screen bg-slate-900 text-slate-100 selection:bg-eco-500/30">
            <NavBar/>
            {children}
            <Footer/>
        </div>
        </body>
        </html>
    );
}
